# Generated by Django 3.2.5 on 2021-07-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='buyer',
            field=models.BooleanField(default=False, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Прошел активацию?'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='seller',
            field=models.BooleanField(default=True, verbose_name='Продавец'),
        ),
    ]
