# Generated by Django 3.2.5 on 2021-07-12 10:05

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_auto_20210711_1643"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=main.utilities.get_timestamp_path,
                verbose_name="Изображение",
            ),
        ),
    ]
