# Generated by Django 3.2.5 on 2021-07-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_tip_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tip",
            name="product_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.subproduct",
                verbose_name="Название продукта",
            ),
        ),
    ]
