# Generated by Django 3.2.5 on 2021-07-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_tip_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Название продукта'),
        ),
    ]
