# Generated by Django 3.2.5 on 2021-07-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_tip_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='id_tip',
            field=models.IntegerField(db_index=True, default=0, unique=True, verbose_name='Id ставки'),
        ),
    ]
