# Generated by Django 3.2.5 on 2021-07-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_tip_id_tip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tip",
            name="id_tip",
        ),
    ]
