# Generated by Django 3.2.5 on 2021-08-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_tip_value_tip"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="deadline",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Завершается прием ставок на продукт",
            ),
        ),
        migrations.AlterField(
            model_name="tip",
            name="value_tip",
            field=models.IntegerField(verbose_name="Ваша ставка"),
        ),
    ]
