# Generated by Django 3.2.5 on 2021-08-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_auto_20210807_1332"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="deadline",
            field=models.DateTimeField(
                verbose_name="Завершается прием ставок на продукт"
            ),
        ),
    ]
