# Generated by Django 3.2.5 on 2022-03-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_product_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='last_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
